### ISSUE TITLE
Upgrade PostgreSQL version

### ISSUE THREAD

**Issue by esune** [bcgov/orgbook-configurations#94]
The templates are still using PostgreSQL 10, we should update them to use the newer version of PostgreSQL 12.

Options are:
- switch to using the `registry.redhat.io/rhscl/postgresql-12-rhel7` image from the RedHat catalog
- use the available PostgreSQL 12 ImageStream in the `openshift` namespace, see example [here](https://github.com/bcgov/representation-grant-app/tree/main/openshift/templates/db)

The work should be PR'd back into the `feature/ocp4` branch.

**Comment by esune** [comment]
@wadeking98 can you please provide a description of the procedure that is required for the upgrade to work, so we have a reference?

**Comment by wadeking98** [comment]
@esune @WadeBarnes Sure, I've updated the build image in my fork to pull postgres 12, the only issue is that the existing data isn't compatible with postgres 12 and needs to be updated as well. There are a couple techniques using things like pg_upgrade, however I remember running into a couple issues using this tool. I think pg_upgrade might require root access in the container. The way I did it (by accident) was to recreate the data from backup. This works but it's not very practical since the data has to be re indexed by the search engine which can take several hours for just over a million credentials. I would spend a bit more time experimenting with the recommended tools like pg_upgrade

**Comment by WadeBarnes** [comment]
@wadeking98, if the supported database upgrade procedure for the container does not work, [Upgrading database (by switching to newer PostgreSQL image version)](https://github.com/sclorg/postgresql-container/tree/generated/12#upgrading-database-by-switching-to-newer-postgresql-image-version), use the backup and restore method using the `backup-container`.

**Comment by wadeking98** [comment]
since the wallet and db have been restored on pg12 can we close this issue?
